name: my_first_project
description: A new Flutter project for Linkedin Learning.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  url_launcher: ^6.2.1
  social_media_buttons: ^1.0.0
  json_annotation: ^4.8.1
  http: ^1.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:

  uses-material-design: true

  assets:
     - assets/chatimage.png
     - assets/mock_messages.json
